server:
  port: 10000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysqlex?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: spring
    password: 1234
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml
  type-handlers-package: com.example.mysql.mybatis.handler